language: haskell
ghc: 7.8

before_install:
  - Xvfb -screen 0 1024x768x24 &
  - wget -O sublime_text.tar.bz2 http://c758482.r82.cf2.rackcdn.com/sublime_text_3_build_3065_x64.tar.bz2
  - tar -xvf sublime_text.tar.bz2
  - "export SUBLIME_PATH=sublime_text_3/sublime_text"
  - sudo apt-add-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get update
  - sudo apt-get install python3.4
  - sudo ln /usr/bin/python3.4 /usr/bin/python3

install: echo Do nothing

script:
  - bash run_tests.sh
  - DISPLAY=:0 bash run_integ_tests.sh