language: python

python:
  - "3.3"

before_install:
  - wget -O sublime_text.tar.bz2 http://c758482.r82.cf2.rackcdn.com/sublime_text_3_build_3065_x64.tar.bz2
  - tar -xvf sublime_text.tar.bz2
  - "export SUBLIME_PATH=sublime_text_3/sublime_text"
  - Xvfb -screen 0 1024x768x24 &
  - sudo apt-add-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install xlib1g-dev ghc-7.8.3
  - export PATH="/opt/ghc/7.8.3/bin:$PATH"
  - wget -O cabal-install https://www.haskell.org/cabal/release/cabal-install-1.20.0.3/cabal-install-1.20.0.3.tar.gz
  - tar -xvf cabal-install
  - cd cabal-install-1.20.0.3
  - bash bootstrap.sh
  - export PATH="$HOME/.cabal/bin:$PATH"

script:
  - bash run_tests.sh
  - bash run_integ_tests.sh