language: python

python:
  - "3.3"

before_install:
  - wget -O sublime_text.tar.bz2 http://c758482.r82.cf2.rackcdn.com/sublime_text_3_build_3065_x64.tar.bz2
  - tar -xvf sublime_text.tar.bz2
  - "export SUBLIME_PATH=sublime_text_3/sublime_text"
  - sudo apt-get install xvfb
  - sudo apt-get install libgtk2.0-0

script:
  - bash run_tests.sh
  - xvfb -screen 0 1024x768x24
  - bash run_integ_tests.sh